import Head from "next/head";
import Layout from "../components/Layout";
import { Divider } from "@mantine/core";
import Hero from "../components/Hero";

import Services from "../components/Services";
import css from '../styles/Home.module.css'


export default function Home() {
  return (
    <Layout>
    
   
      <div className={css.container}>
        <Head>
          <title>Ahar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logoAhar.png" />
        </Head>
        {/* body */}
        <main>
        
          <Hero/>    
          <Services/>   
        </main>
      </div>
      </Layout>
     
    
  );
  }

